builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - freebsd
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - mips
  - mipsle
  - mips64
  goarm:
  - 5
  - 6
  - 7
archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  format: gz
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: tuotoo
    name: qiniu-auto-cert
  draft: true
  prerelease: true
changelog:
  skip: true

