builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - LICENCE
    - README.md
    - res/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: tuotoo
    name: qiniu-auto-cert
git:
  short_hash: true
